baseurl = "http://abirger.github.io/sos-guidelines"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
languageCode = "en-us"
Title = "IOOS SOS Guidelines"
[params]
 Description = "Docs, codes, scripts, templates"
 Copyright = "(C) 2014 U.S. IOOS. Some rights reserved"


	
	
 
